### ISSUE TITLE
Run tests against MongoDB 6 and 7

### ISSUE THREAD

**Issue by dblock** [mongoid/mongoid-compatibility#17]
Run tests against MongoDB 6 and 7.

**Comment by dblock** [comment]
@sairamsrinivasan Want to pick this one up too?

**Comment by sairamsrinivasan** [comment]
@dblock - I can take a look at this when I get chance!

**Comment by dblock** [comment]
Closed via https://github.com/mongoid/mongoid-compatibility/pull/18.
